// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DelFunc is an autogenerated mock type for the DelFunc type
type DelFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DelFunc) Execute(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
