// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExistsFunc is an autogenerated mock type for the ExistsFunc type
type ExistsFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ExistsFunc) Execute(_a0 string) (*bool, error) {
	ret := _m.Called(_a0)

	var r0 *bool
	if rf, ok := ret.Get(0).(func(string) *bool); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
