// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	encoding "encoding"

	mock "github.com/stretchr/testify/mock"
)

// GetFunc is an autogenerated mock type for the GetFunc type
type GetFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *GetFunc) Execute(_a0 string, _a1 encoding.BinaryUnmarshaler) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, encoding.BinaryUnmarshaler) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
