// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SetFunc is an autogenerated mock type for the SetFunc type
type SetFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *SetFunc) Execute(_a0 string, _a1 interface{}, _a2 time.Duration) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, time.Duration) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSetFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewSetFunc creates a new instance of SetFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSetFunc(t mockConstructorTestingTNewSetFunc) *SetFunc {
	mock := &SetFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
