basePath: /
definitions:
  sample.sampleResource:
    properties:
      wibble:
        type: string
    type: object
  sample.sampleResp:
    properties:
      request_id:
        type: string
      token_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample service for simian go
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Sample API
  version: "1.0"
paths:
  /sample/{id}:
    post:
      consumes:
      - application/json
      description: one saple endpoint
      parameters:
      - description: Sample Resource
        in: body
        name: resource
        required: true
        schema:
          $ref: '#/definitions/sample.sampleResource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sample.sampleResp'
      summary: sample simian go api
      tags:
      - sample
swagger: "2.0"
