global:
  scrape_interval: 7s
  scrape_timeout: 3s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'host.docker.internal:5100'
