version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=hostfilesentinalentry
    ports:
      - '26379:26379'
  mssql:
    build:
      context: ./mssql/
      dockerfile: ./Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Melon40twomonkeys
    ports:
      - '1433:1433'
  pg:
    build:
      context: ./pg/
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=Melon40twomonkeys
    ports:
      - '5432:5432'
