---
name: deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: make test

      - name: Post Coverage
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v4.2.0
        with:
          file: coverage.out
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          file: junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  update-release-draft:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
